import = ["/home/vi/.config/alacritty/catppuccin-latte.toml"]

[font]
size = 14.0

[font.normal]
family = "Hack Nerd Font Mono"

[window]
dynamic_title = true
# opacity = 0.95
startup_mode = "Maximized"
title = "Alacritty"
# "window.decorations_theme_variant" = "dark"
