use-grammars = { only = [ 
    "rust", 
    "c", 
    "cpp" , 
    "racket", 
    "py", 
    "toml", 
    "md",
    "json",
    "html",
    "fish",
    "gitignore"
] }
[[language]]
name = "rust"

[language.config.check]
command = "clippy"

[[language]]
name = "python"
auto-format = true
# formatter = { command = "black", args = ["--line-length", "120"]}
[language.formatter]
command = "black"
args = [
    "-", # stdin
    "--line-length=100",
]

[[language]]
name = "c"
config = { enable = true, lint = true, unstable = true }
auto-format = true
indent = { tab-width = 3, unit = "   " }

[[language]]
name = "toml"
auto-format = true

[[language]]
name = "racket"
auto-format = true
indent = {tab-width = 2, unit = " "}
language-server = { command = "racket", args = ["-l", "racket-langserver"] }
