use-grammars = { only = [ 
    "rust", 
    "c", 
    "cpp" , 
    "py", 
    "toml", 
    "md",
    "json",
    "html",
    "fish",
    "gitignore",
    "go"
] }

[[language]]
name = "markdown"
soft-wrap.enable = true
[language.auto-pairs]
'(' = ')'
'{' = '}'
'[' = ']'
'"' = '"'
"'" = "'"
"`" = "`"

[[language]]
name = "rust"
scope = "source.rust"
injection-regex = "rust"
file-types = ["rs"]
roots = ["Cargo.toml", "Cargo.lock"]
auto-format = true
comment-token = "//"
indent = { tab-width = 4, unit = "	" }

[language-server.rust-analyzer.config]
inlayHints.bindingModeHints.enable = false
inlayHints.closingBraceHints.minLines = 10
inlayHints.closureReturnTypeHints.enable = "with_block"
inlayHints.discriminantHints.enable = "fieldless"
inlayHints.lifetimeElisionHints.enable = "skip_trivial"
inlayHints.typeHints.hideClosureInitialization = false

# On older versions of Helix, try using [language.config.check] instead
[language-server.rust-analyzer.config.check]
command = "clippy"


[[language]]
name = "python"
auto-format = true
[language.formatter]
command = "black"
args = [
    "-", # stdin
    "--line-length=100",
]

[[language]]
name = "c"
# config = { enable = true, lint = true, unstable = true }
auto-format = true
indent = { tab-width = 3, unit = "   " }
[language-server.clangd.config]
lint = "true"
unstable = "true"

[[language]]
name = "toml"
auto-format = true

[[language]]
name = "javascript"
auto-format = true
indent = {tab-width = 2, unit = " "}
[language-server.typescript-language-server.config]
display-inlay-hints = false

[[language]]
name = "go"
auto-format = true
formatter = {command = "goimport"}
